# Veritabanı Bağlantı Adresi (Buzdolabının Konumu)
spring.datasource.url=jdbc:postgresql://localhost:5432/vigilant_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları (Tabloları Otomatik Oluşturma)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8081
# Kafka Kurye Merkezi Adresi
